// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/api/joke.ts";
import * as $1 from "./routes/details/[slug].tsx";
import * as $2 from "./routes/index.tsx";
import * as $3 from "./routes/login.tsx";
import * as $4 from "./routes/short/[slug].tsx";

const manifest = {
  routes: {
    "./routes/api/joke.ts": $0,
    "./routes/details/[slug].tsx": $1,
    "./routes/index.tsx": $2,
    "./routes/login.tsx": $3,
    "./routes/short/[slug].tsx": $4,
  },
  islands: {},
  baseUrl: import.meta.url,
};

export default manifest;
